{% set name = "pystac" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystac-{{ version }}.tar.gz
  sha256: a01da05cb29d0eb995a11e32a6d15067f653ceb8c64f61f912ac99c7e9ff4f2e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - python-dateutil >=2.7.0

test:
  imports:
    - pystac
    - pystac.extensions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stac-utils/pystac
  summary: Python library for working with Spatiotemporal Asset Catalog (STAC)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gadomski
    - ocefpaf
