{% set python_min = "3.10" %}
{% set name = "pystac" %}
{% set version = "1.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pystac-{{ version }}.tar.gz
  sha256: dc68bd4d24f391306caf89d2547015d8b0d6907bb72f7a431cff2dc86b6bdf16

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.7.0

test:
  imports:
    - pystac
    - pystac.extensions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stac-utils/pystac
  summary: Python library for working with Spatiotemporal Asset Catalog (STAC)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gadomski
    - ocefpaf
